### ISSUE TITLE
Tooltips stuck on Please Wait...

### ISSUE THREAD

**Issue by jburleigh1** [osrsbox/osrsbox-tooltips#14]
Hey again!

Just wanted to report a slight issue in that the tool tips have stopped working!

I came across the issue on my own site today and cross-referenced with your own demo page and I'm seeing the same issue: 

`Cannot read property 'attack_stab' of undefined`

Hopefully it's a quick fix 👍

**Comment by osrsbox** [comment]
Hey @jburleigh1 - crap! I made a change to the item database JSON structure recently, and forgot that it would also break the tooltips library. Thanks so much for letting me know. I just pushed a change in commit 14562435a80e9bb3cc05c3d53763e1b353cc5674 which should fix the problem. Tested briefly, but wanted to get a fix up sooner rather than later.
If there are still problems. Please let me know. Will leave the issue open.... just in case there are still issues.

**UPDATE:**
Just checked your website... and the tooltips are still not working for some reason. I can see your site is downloading the latest file I just uploaded - but it still displaying an error. I think it is because I recently changed `bonuses` to be in `equipment`. So it is `json_data["equipment"]["attack_stab"]` now.

So I think your need to change the following in your JS:
```
e.bonuses.attack_stab
```
to
```
e.equipment.attack_stab
```

Really sorry about this problem.

**Comment by jburleigh1** [comment]
Hey!

Thanks for pushing that fix so quickly, and I went ahead and resolved the issue on my end with a quick find and replace 👍 

All good and working now!
