### ISSUE TITLE
v1.0.3 is broken

### ISSUE THREAD

**Issue by while-loop** [osrsbox/osrsbox-tooltips#15]
When running the [sample_sri.html](https://github.com/osrsbox/osrsbox-tooltips/blob/master/sample/sample_sri.html), I get a `Uncaught TypeError: Cannot read property 'attack_stab' of undefined` error.

The JS code is still looking at the `bonuses` key instead of the new `equipment` key.

**Comment by while-loop** [comment]
(btw, awesome osrs libraries! you're a hero)

**Comment by osrsbox** [comment]
Oh no! Thanks for posting this issue @while-loop. There has been so many updates to the `osrsbox-db` project, and since this tooltips project doesn't get much attention/use I have been slack at updating it. I will update this ASAP to get it working again like it should.

**Comment by osrsbox** [comment]
This was fixed in 4d9a189f256f1b5bcf98479cb22f3e2663b9ee35. The `sample_sri.html` page example was fixed in d8585682e4dad60df81a853a3ab7a63733e5ca55. Version 1.0.4 has the fixed code, as well as the `osrsbox-tooltips.js` and `osrsbox-tooltipcs.css` being updated. The new SRI hashes are available on the repository readme file. 

Thanks @while-loop for pointing out this error. Please feel free to comment/re-open this issue if you are still having problems after the update.
