### ISSUE TITLE
Tooltips are applied to all <a> tags, regardless of class

### ISSUE THREAD

**Issue by jburleigh1** [osrsbox/osrsbox-tooltips#9]
Hey!

So I noticed today that any <a> tag with a title attribute is triggering the jQuery UI tooltip. Ideally, it's only applied to <a> tags with the `.osrstooltip` class.

**Comment by osrsbox** [comment]
Had some time to look into this issue today. Unfortunately, it is not an easy fix. Since the tooltips library relies on the JQuery UI, there are aspects of that library that come with additional functionality (in this case, unwanted functionality). There are two options:
1. Change to JQuery code to remove adding the style to the `.osrstooltip` class
1. Write a new osrstooltip library that does not use JQuery

Both are big jobs. One potential solution is to remove `title` tags (probably not very desirable). Another option is to hide the title attribute on hover (see: https://spigotdesign.com/hide-title-attribute-hover-dont-remove/), this could be a decent option, but will break any other code that uses `title` attribute and hover events. Out of the two options, I am not sure how/where to change the JQuery code, and writing a new tooltip library is a massive job (my JS is not strong). 
If you have any ideas, please feel free to let me know!

**Comment by jburleigh1** [comment]
Hey @osrsbox, is this going to make it into the 1.0.3 release? I think it's my last blocker before I can roll the plugin out across my site and start tool-tippin' it up :)

**Comment by osrsbox** [comment]
Hey @jburleigh1. Yes, I will build a new release today with the new fix. It took a while as I was trying to update the project web page first to align with the flurry of updates we have had lately! But version 1.0.3 should be up in a couple hours!
